version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./init_testfligoo.sql:/docker-entrypoint-initdb.d/init_testfligoo.sql
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  airflow-init:
    image: apache/airflow:2.6.0
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    entrypoint: >
      /bin/bash -c "
      airflow db init &&
      airflow users create -u airflow -p airflow -f Airflow -l Admin -r Admin -e admin@example.com &&
      airflow connections add 'postgres_fligoo' --conn-uri 'postgresql+psycopg2://airflow:airflow@postgres:5432/testfligoo'
      "

  airflow-webserver:
    image: apache/airflow:2.6.0
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__RBAC: 'true'
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.6.0
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
    command: scheduler

  jupyter:
    image: jupyter/datascience-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./default_notebook.ipynb:/home/jovyan/work/default_notebook.ipynb
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "token"
    depends_on:
      - postgres
    command: >
      /bin/bash -c "
      pip install psycopg2-binary &&
      start-notebook.sh
      "
